[package]
name = "aghpb"
description="Anime girls holding programming books API wrapper for ðŸ¦€Rust."
authors = ["Goldy"]
license-file = "LICENSE"
edition = "2021"
version = "0.1.0"

[dependencies]
reqwest = "0.11.18"
image = "0.24.6"
serde_json = "1"